sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 
    database: sky_take_out
    username: root
    password: 
  alioss:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 
  redis:
    host: 
    port: 6379
    password: 
    database: 1
#  wechat:
#    appid: 
#    secret: 
  shop:
    address: 
  baidu:
    ak: 
